// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://upctmnieyczjkjitjvyt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwY3RtbmlleWN6amtqaXRqdnl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNTI4NTMsImV4cCI6MjA2MzcyODg1M30.z1E4UdfhQN2LLearkcQD1mjARPYz33L58aVzPjxlM-E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);